Neos:
  Flow:
    i18n:
      defaultLocale: de
      fallbackRule:
        order:
          - de
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              Sandstorm.UserManagement:NeosBackend:
                pattern: Sandstorm\UserManagement\Security\NeosRequestPattern
                patternOptions:
                  'area': 'backend'
          'Sandstorm.UserManagement:Login':
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              Sandstorm.UserManagement:NeosFrontend:
                pattern: Sandstorm\UserManagement\Security\NeosRequestPattern
                patternOptions:
                  'area': 'frontend'
  Form:
    yamlPersistenceManager:
      savePath: 'resource://Ws.Fshsite/Private/Form/'
    presets:
      default:
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Ws.Fshsite/Private/Templates/ContactForm/{@type}.html'
          'Neos.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://Ws.Fshsite/Private/Form/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: form-control
          'Neos.Form:IntegerField':
            superTypes:
              'Neos.Form:SingleLineText': true

  ContentRepository:
    Search:
      # API. If set to FALSE, only index the "live" workspace and not user workspaces.
      # If you only index the live workspace, Search will not work for your editors in the user workspaces.
      # Furthermore, if you heavily rely on Search for collecting content, this might be strange for editors to
      # work with -- as unpublished changes are not indexed right away.
      indexAllWorkspaces: false
  Neos:
    userInterface:
      editPreviewModes:
        print:
          isEditingMode: false
          isPreviewMode: true
          typoScriptRenderingPath: print
          title: 'Print'
          position: 200
      translation:
        autoInclude:
          Ws.Fshsite:
            - Main
            - 'NodeTypes/*'
      inspector:
        dataTypes:
          Neos\Media\Domain\Model\ImageInterface:
            editorOptions:
              features:
                resize: true
      defaultLanguage: de

Sandstorm:
  UserManagement:
    # Validity timespan for the activation token for newly registered users.
    activationTokenTimeout: '14 days'
    # Validity timespan for the token used to reset passwords.
    resetPasswordTokenTimeout: '4 hours'
    # The message that appears if a user could not be logged in.
    authFailedMessage:
      title: 'Login nicht möglich'
      body: 'Sie haben ungültige Zugangsdaten eingegeben. Bitte versuchen Sie es noch einmal.'
    # Email settings
    email:
      # Subject line for the account confirmation email
      subjectActivation: 'E-Mail-Adresse bestätigen'
      # Subject line for the password reset email
      subjectResetPassword: 'Passwort neu setzen'
    # An array of roles which are assigned to users after they activate their account.
    rolesForNewUsers: ['Flowpack.Neos.FrontendLogin:FSH_Mitglied']
  TemplateMailer:
    templatePackages:
      10: 'Ws.Fshsite'
    senderAddresses:
      'sandstorm_usermanagement_sender_email': # You need to use this exact key to override the UserManagement defaults
        name: 'FSH Mitglieder Registrierung'
        address: 'keine-antwort@frauenselbsthilfe.de'
    replyToAddresses:
      'sandstorm_usermanagement_replyTo_email':
        name: 'FSH Mitglieder Registrierung'
        address: 'keine-antwort@frauenselbsthilfe.de'

Flowpack:
  ElasticSearch:
    ContentRepositoryAdaptor:
      driver:
        version: 1.x

Networkteam:
  Neos:
    Shariff:
      options:
        services:
          - Twitter
          - Facebook
          - GooglePlus

DL:
  Gallery:
    loadGalleryCSS: true
    loadGalleryJS: true
    themes:
      bootstrapLightbox:
        label: 'Bootstrap with Lightbox'
        themeSettings:
          columnClass: col-sm-4
          imageVariants:
            thumb:
              maximumWidth: null
              maximumHeight: null
              width: 600
              height: 600
              allowCropping: true
              allowUpScaling: null
            large:
              maximumWidth: 2000
              maximumHeight: 1200
              width: null
              height: null
              allowCropping: null
              allowUpScaling: null

Lelesys:
  News:
    view:
      list:
        thumbnailMaxWidth: 160
        thumbnailMaxHeight: 160
        
KaufmannDigital:
  CookieConsent:
    #Global configuration of PolicyPage
    policyPageNode: 'c7a8b6fd-c191-451e-b707-60a590cd83da' #UUID of global page you want to link

    ##Configuration per site for multisite installations
    ##Replace site1/site2 with your sitename (/sites/sitename/node-a2ufd/.../)
    #policyPageNodes:
    #  site1: 'c7a91aa8-fbac-4c24-8326-102eb7307180' #UUID of policy-page for /sites/site1
    #  site2: '454d85b6-289b-11e9-b210-d663bd873d93' #UUID of policy-page for /sites/site2
